RegisterNetEvent('esx_interact:handcuff')
AddEventHandler('esx_interact:handcuff', function(target)
	TriggerClientEvent('esx_interact:handcuff', target)
end)

RegisterNetEvent('esx_interact:putInVehicle')
AddEventHandler('esx_interact:putInVehicle', function(target)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_interact:putInVehicle', target)
end)

RegisterNetEvent('esx_interact:OutVehicle')
AddEventHandler('esx_interact:OutVehicle', function(target)
	local xPlayer = ESX.GetPlayerFromId(source)
	TriggerClientEvent('esx_interact:OutVehicle', target)
end)
