Config                            = {}

Config.EnableHandcuffTimer        = true -- Enable handcuff timer? will unrestrain player after the time ends.
Config.HandcuffTimer              = 10 * 60000 -- 10 minutes.
Config.ShowNotificationText       = "La personne doit être menottée où lever les bras"
Config.RequiredItem               = "Vous avez besoin de menotte ou d'une corde"
Config.Unrestrained_timer         = "Vous sentez que vos menottes deviennent fragiles"
Config.search                     = "Fouiller"
Config.search_img                 = "fa-solid fa-person"
Config.handcuff                   = "Menotter"
Config.handcuff_img               = "fa-solid fa-handcuffs"
Config.putveh                     = "Mettre dans véhicule"
Config.putveh_img                 = "fa-solid fa-people-pulling"
Config.ID                         = "Regarder carte identité"
Config.ID_img                     = "fa-solid fa-id-card"
Config.ID_driver                  = "Regarder permis de conduite"
Config.ID_driver_img              = "fa-solid fa-id-card-clip"
Config.outveh                     = "Sortir du véhicule"
Config.outveh_img                 = "fa-solid fa-people-pulling"
